### ISSUE TITLE
add git proxy support

### ISSUE THREAD

**Issue by Heavenser** [funtoo/ego#17]
Hello, it's very slow to access github.com in my country, can you add git proxy support for ego? Thank you.

**Comment by palica** [comment]
you can use your own git server with this setting:

```
[global]
sync_base_url=https://your.git.server/funtoo/{repo}

```

but would have to mirror repositories from https://github.com/funtoo/meta-repo + all *-kit repos.

**Comment by Heavenser** [comment]
thank you!
